## Machine  Learning Models

Loading dataset

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r'ready_data.csv')
df.head()

,Trans_Amount,Amount_paid,Speed,Fraud_indicator,Hour,DayOfWeek,Month,Veh_Type_Bus,Veh_Type_Car,Veh_Type_Motorcycle,...,Lane_Type_Express,Lane_Type_Regular,Veh_Dimensions_Large,Veh_Dimensions_Medium,Veh_Dimensions_Small,"Geo_location_12.84197701525119, 77.67547528176169","Geo_location_12.936687032945434, 77.53113977439017","Geo_location_13.042660878688794, 77.47580097259879","Geo_location_13.059816123454882, 77.77068662374292","Geo_location_13.21331620748757, 77.55413526894684"
0,350,120,65,0,11,4,1,1,0,0,...,1,0,1,0,0,0,0,0,1,0
1,120,100,78,0,14,5,1,0,1,0,...,0,1,0,0,1,0,0,0,1,0
2,0,0,53,1,18,6,1,0,0,1,...,0,1,0,0,1,0,0,0,1,0
3,350,120,92,0,2,0,1,0,0,0,...,0,1,1,0,0,0,0,0,1,0
4,140,100,60,0,6,1,1,0,0,0,...,1,0,0,1,0,0,0,0,1,0

## Splittinng the data into x and y

In [7]:
x = df.drop(columns='Fraud_indicator', axis=1 )
x.head()

,Trans_Amount,Amount_paid,Speed,Hour,DayOfWeek,Month,Veh_Type_Bus,Veh_Type_Car,Veh_Type_Motorcycle,Veh_Type_SUV,...,Lane_Type_Express,Lane_Type_Regular,Veh_Dimensions_Large,Veh_Dimensions_Medium,Veh_Dimensions_Small,"Geo_location_12.84197701525119, 77.67547528176169","Geo_location_12.936687032945434, 77.53113977439017","Geo_location_13.042660878688794, 77.47580097259879","Geo_location_13.059816123454882, 77.77068662374292","Geo_location_13.21331620748757, 77.55413526894684"
0,350,120,65,11,4,1,1,0,0,0,...,1,0,1,0,0,0,0,0,1,0
1,120,100,78,14,5,1,0,1,0,0,...,0,1,0,0,1,0,0,0,1,0
2,0,0,53,18,6,1,0,0,1,0,...,0,1,0,0,1,0,0,0,1,0
3,350,120,92,2,0,1,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
4,140,100,60,6,1,1,0,0,0,0,...,1,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,330,330,81,22,6,1,0,0,0,0,...,0,1,1,0,0,0,0,0,0,1
4996,125,125,64,13,1,1,0,0,0,0,...,1,0,0,1,0,0,0,0,0,1
4997,115,115,93,5,6,2,0,0,0,0,...,0,1,0,1,0,0,0,0,0,1
4998,145,145,57,20,0,2,0,0,0,1,...,1,0,1,0,0,0,0,0,0,1
4999,330,125,86,0,4,3,1,0,0,0,...,0,1,1,0,0,0,0,0,0,1

In [8]:
y = df['Fraud_indicator']

y.head()

0    0
1    0
2    1
3    0
4    0
Name: Fraud_indicator, dtype: int64

### Splittinng into  train set and test set

In [15]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.8)

## Logistic Regression Model

### Cross Validation

In [56]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
import warnings

# Filter out future warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Creating a pipeline that scales the data and then applies Logistic Regression
logistic_model=make_pipeline(StandardScaler(),LogisticRegression(max_iter=100))

# Fit the model on the training data
logistic_model.fit(x_train, y_train)

# Perform cross-validation
scores = cross_val_score(logistic_model, x, y, cv=5)  


# Print the scores for each fold
print("Cross-Validation Scores:", scores)

# Print the average score
print("Average Score:", scores.mean())

Cross-Validation Scores: [0.984 0.962 0.957 0.969 0.972]
Average Score: 0.9687999999999999

## Inights
1. There's a slight variation in scores across different folds, but all scores are relatively high. This is a good sign of the model's robustness and its ability to generalize across different data samples.

### Test Metrics

In [61]:

# Predict on the test data
y_pred = logistic_model.predict(x_test)

# Print the classification report
print("Test Metrics Report:\n" , classification_report(y_test, 
                                y_pred, target_names=['Not Fraud', 'Fraud']))

Test Metrics Report:
               precision    recall  f1-score   support

   Not Fraud       1.00      0.88      0.93       195
       Fraud       0.97      1.00      0.99       805

    accuracy                           0.98      1000
   macro avg       0.99      0.94      0.96      1000
weighted avg       0.98      0.98      0.98      1000

## Insights
1. The model indicates excellent performance in identifying fraudulent transactions with very few false positives and almost no false negatives.
2. The recall for 'Not Fraud' is 0.88 which suggests that some legitimate transactions are being misclassified as fraudulent.

## Training Metrics

In [62]:
from sklearn.metrics import classification_report

y_train_pred = logistic_model.predict(x_train)

train_report = classification_report(y_train, y_train_pred, 
                                     target_names=['Not Fraud', 'Fraud'])

print("Training Metrics Report:\n", train_report)

Training Metrics Report:
               precision    recall  f1-score   support

   Not Fraud       1.00      0.85      0.92       788
       Fraud       0.97      1.00      0.98      3212

    accuracy                           0.97      4000
   macro avg       0.98      0.93      0.95      4000
weighted avg       0.97      0.97      0.97      4000

## Insights
Overall accuracy on the training set is 0.97, which is slightly lower than the test set. This is somewhat unusual as models typically perform better on the training data.

## Random Forest Model

## cross-validation

In [49]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Initializing the RandomForestClassifier
randf_model = RandomForestClassifier(max_depth=15, n_jobs=-1)

# Fit the model on the training data
randf_model.fit(x_train, y_train)

# Perform cross-validation
scores = cross_val_score(randf_model, x, y, cv=5)  # 'cv' is the number of folds

# Print the scores for each fold
print("Cross-Validation Scores:", scores)

# Print the average score
print("Average Score:", scores.mean())

Cross-Validation Scores: [0.98  0.971 0.97  0.978 0.987]
Average Score: 0.9772000000000001

## Insights
1. The scores for each fold  shows that the model's performance is quite consistent across different subsets of data.
2. There are no extreme variations in performance across folds, which is a good sign of the model's stability and generalizability.
3. A high average score like this, indicates that the model is likely to perform well on unseen data.

## Testing Metrics

In [50]:

# Predict on the test data
y_pred = randf_model.predict(x_test)

# Print the classification report
print("Test Metrics Report:\n" , classification_report(y_test, 
                                y_pred, target_names=['Not Fraud', 'Fraud']))

Test Metrics Report:
               precision    recall  f1-score   support

   Not Fraud       1.00      0.95      0.97       195
       Fraud       0.99      1.00      0.99       805

    accuracy                           0.99      1000
   macro avg       0.99      0.97      0.98      1000
weighted avg       0.99      0.99      0.99      1000

### Insights
1. The model shows robustness in classifying both classes, with high accuracy (0.99) on the test set.
2. The macro and weighted averages on the test set (0.98 and 0.99, respectively) indicate balanced performance across classes, despite the potential class imbalance (more 'Fraud' instances than 'Not Fraud').

## Training metrics

In [45]:
from sklearn.metrics import classification_report

y_train_pred = randf_model.predict(x_train)

train_report = classification_report(y_train, y_train_pred, 
                                     target_names=['Not Fraud', 'Fraud'])

print("Training Metrics Report:\n", train_report)

Training Metrics Report:
               precision    recall  f1-score   support

   Not Fraud       1.00      1.00      1.00       788
       Fraud       1.00      1.00      1.00      3212

    accuracy                           1.00      4000
   macro avg       1.00      1.00      1.00      4000
weighted avg       1.00      1.00      1.00      4000

###### Excellent Training Performance:
This model achieves perfect precision, recall, and F1-scores of 1.00 for both classes ('Not Fraud' and 'Fraud') on the training data. This indicates that the model is able to perfectly classify all training instances.